# Generated by Django 4.2.5 on 2023-12-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', models.IntegerField(max_length=99)),
                ('backend', models.IntegerField(max_length=99)),
                ('flat', models.IntegerField(max_length=9999)),
            ],
        ),
    ]
