# Generated by Django 4.2.5 on 2023-12-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payplan',
            name='backend',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payplan',
            name='flat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payplan',
            name='frontend',
            field=models.IntegerField(),
        ),
    ]
