# Generated by Django 4.2.5 on 2023-12-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0002_alter_payplan_backend_alter_payplan_flat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volumebump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitcount', models.IntegerField(null=True)),
                ('bonus', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='payplan',
            name='volumebonus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='unitbonus', to='payplan.volumebump'),
            preserve_default=False,
        ),
    ]
