# Generated by Django 4.2.5 on 2023-12-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0004_alter_volumebump_bonus_alter_volumebump_unitcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payplan',
            name='volumebonus',
        ),
        migrations.DeleteModel(
            name='Volumebump',
        ),
    ]
