# Generated by Django 4.2.5 on 2023-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0005_remove_payplan_volumebonus_delete_volumebump'),
    ]

    operations = [
        migrations.AddField(
            model_name='payplan',
            name='totalsales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
