# Generated by Django 4.2.5 on 2023-12-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0007_rename_frontend_payplan_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payplan',
            name='flat',
        ),
    ]
