# Generated by Django 4.2.5 on 2023-12-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0009_alter_payplan_commission_alter_payplan_totalsales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payplan',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
