# Generated by Django 4.2.5 on 2023-12-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0010_alter_payplan_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.IntegerField()),
            ],
        ),
    ]
