# Generated by Django 4.2.5 on 2023-12-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0011_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
            ],
        ),
    ]
