# Generated by Django 4.2.5 on 2023-12-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0018_alter_sale_datelogged'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=0)),
                ('sales_required', models.IntegerField(default=0)),
            ],
        ),
    ]
