# Generated by Django 4.2.5 on 2023-12-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0019_volumebonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_amount', models.IntegerField(default=0)),
                ('sales_required', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='volumebonus',
            options={'verbose_name_plural': 'volume bonuses'},
        ),
    ]
