# Generated by Django 4.2.5 on 2023-12-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0022_flat_user_id_volumebonus_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
