# Generated by Django 4.2.5 on 2023-12-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0024_alter_sale_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('store_code', models.CharField(max_length=50)),
            ],
        ),
    ]
