# Generated by Django 4.2.5 on 2023-12-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payplan', '0025_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
